/*
-----------------------------------------------------------------------------
Filename:    BaseApplication.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.7.x Application Wizard for VC10 (July 2011)
      http://code.google.com/p/ogreappwizards/
-----------------------------------------------------------------------------
*/
#ifndef __BaseApplication_h_
#define __BaseApplication_h_

#include <OgreCamera.h>
#include <OgreEntity.h>
#include <OgreLogManager.h>
#include <OgreRoot.h>
#include <OgreViewport.h>
#include <OgreSceneManager.h>
#include <OgreRenderWindow.h>
#include <OgreConfigFile.h>

#include <OISEvents.h>
#include <OISInputManager.h>
#include <OISKeyboard.h>
#include <OISMouse.h>

#include <SdkTrays.h>
#include <SdkCameraMan.h>
#include "BowlingBall.h"
#include "Pin.h"
#include "Arrow.h"
#include "PinManager.h"
#include "Gui3D.h"
#include "Gui3DPanel.h"
#include "Gui3DPanelColors.h"
#include "MyPurplePanelColors.h"
#include "Gui3DProgressBar.h"

//FMOD includes
#pragma comment(lib,"fmodex_vc.lib") 
#include "fmod.hpp"

class BaseApplication : public Ogre::FrameListener, public Ogre::WindowEventListener, public OIS::KeyListener, public OIS::MouseListener, OgreBites::SdkTrayListener
{
public:
    BaseApplication(void);
    virtual ~BaseApplication(void);
	
    virtual void go(void);
	bool tempMove;
	bool loopSong;
	int gameState;
	int gameplay;
	bool menu;

protected:
	virtual bool setup();
    virtual bool configure(void);
    virtual void chooseSceneManager(void);
    virtual void createCamera(void);
    virtual void createFrameListener(void);
    virtual void createScene(void) = 0; // Override me!
    virtual void destroyScene(void);
    virtual void createViewports(void);
    virtual void setupResources(void);
    virtual void createResourceListener(void);
    virtual void loadResources(void);

    // Ogre::FrameListener
    virtual bool frameRenderingQueued(const Ogre::FrameEvent& evt);
	virtual void UpdateCamera();//Controls which camera position the camera goes to
	virtual void UpdateBall();//controls changes to the ball
	virtual void TurnControl();//manages the changing of the turn a player is on
	virtual void DrawTutorial();//used to control if the tutorial options are shown
	virtual void PlayerUpdate();//changes which player is getting updated
	virtual void BallChange(); //Changes the mesh for the ball to differentiate the players
	virtual void DrawStats();//Updates the stats screen when called/ Draws it in player view
	virtual void CreateTextZones();//Used for creting the stats screen on build
	virtual void CheckStrike();//checks if all pins are knocked in one throw 
	virtual void UpdateMenu();//controls the on screen menu
	virtual void CheckWin();//checks the scores and causes a win scenario
	virtual void PinSounds();
	bool PlayGame(Gui3D::PanelElement* e);//two methods called by the menu buttons
	bool QuitGame(Gui3D::PanelElement* e);//

	 Ogre::Vector2 getScreenCenterMouseDistance();

    // OIS::KeyListener
    virtual bool keyPressed( const OIS::KeyEvent &arg );
    virtual bool keyReleased( const OIS::KeyEvent &arg );
    // OIS::MouseListener
    virtual bool mouseMoved( const OIS::MouseEvent &arg );
    virtual bool mousePressed( const OIS::MouseEvent &arg, OIS::MouseButtonID id);
    virtual bool mouseReleased( const OIS::MouseEvent &arg, OIS::MouseButtonID id);

    // Ogre::WindowEventListener
    //Adjust mouse clipping area
    virtual void windowResized(Ogre::RenderWindow* rw);
    //Unattach OIS before window shutdown (very important under Linux)
    virtual void windowClosed(Ogre::RenderWindow* rw);

    Ogre::Root *mRoot;
    Ogre::Camera* mCamera;
    Ogre::SceneManager* mSceneMgr;
    Ogre::RenderWindow* mWindow;
    Ogre::String mResourcesCfg;
    Ogre::String mPluginsCfg;
	
	// Gui3D main object
	Gui3D::Gui3D* mGui3D;
	


	Gui3D::Panel* tutorialPan;
	Gui3D::TextZone* tutorialHeader;

	Gui3D::Panel* tutorialPan2;
	Gui3D::TextZone* tutorialTxt;
	//Gui3D::Caption* tutorialTxt;
	
	// The main panel (display in 3D)
	Gui3D::Panel* mPanel; //displays the power
	Gui3D::Panel* playerPanel;//displays stats to player
	Gui3D::ProgressBar* mForceProgressBar; //the power bar
	MyPurplePanelColors mMyPurplePanelColors;

    // OgreBites
    OgreBites::SdkTrayManager* mTrayMgr;
    OgreBites::SdkCameraMan* mCameraMan;     // basic camera controller
    bool mCursorWasVisible;                  // was cursor visible before dialog appeared
    bool mShutDown;
	int camChange;//an integer that stands for a preset camera position
	float ballpow;//power to be given to ball. Displayed in the power bar
	int playerNum;//The integer that determines which 
	int turnNum;//added
	int p1Score;//added
	int p2Score; //added
	bool drawStats;//added
	bool pressZ,pressX; //allows the player to move
	bool tutorial;//Is set true to show tutorial in the beginning
	int captionNum;
	bool p1Strike,p2Strike;
	bool p1Win,p2Win;
	int winScore;

	Gui3D::TextZone* player;
	Gui3D::TextZone* shot;
	Gui3D::TextZone* player1Score;
	Gui3D::TextZone* player2Score;
	Gui3D::TextZone* pins;

	//menu
	Gui3D::Panel* menuPanel;
	Gui3D::Panel* winMenu;
Gorilla::Layer* mMousePointerLayer;
    Gorilla::Rectangle* mMousePointer;
    Ogre::Vector2 mNormalizedMousePosition;
Ogre::Vector3 cameraDirection;
Gui3D::Caption* captionT;



    //OIS Input devices
    OIS::InputManager* mInputManager;
    OIS::Mouse*    mMouse;
    OIS::Keyboard* mKeyboard;
	BowlingBall* mBallObject;//added
	Arrow* mArrowObject;//added
	PinManager* pinManager;
	FMOD::Channel *channel;
	FMOD::Channel *channelBack;
	
	FMOD::Sound *soundThrow;
	FMOD::Sound *soundRoll;
	FMOD::Sound *backgSnd;



	FMOD::System *FMODsys; //the FMOD sytem
	FMOD::Reverb *reverb;
	FMOD_RESULT result;
};

#endif // #ifndef __BaseApplication_h_
